// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Assignment
{
    public Guid AssignmentId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public string Status { get; set; }

    public byte? PriorityId { get; set; }

    public int? EstimatedTime { get; set; }

    public Guid? SubjectId { get; set; }

    public Guid? UserId { get; set; }

    public virtual PriorityLevel Priority { get; set; }

    public virtual ICollection<Reminder> Reminders { get; set; } = new List<Reminder>();

    public virtual Subject Subject { get; set; }

    public virtual ICollection<TimeLog> TimeLogs { get; set; } = new List<TimeLog>();
    
    public virtual User User { get; set; }
}