// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Budget
{
    public Guid BudgetId { get; set; }

    public Guid? CategoryId { get; set; }

    public Guid? AccountId { get; set; }

    public decimal BudgetAmount { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public Guid UserId { get; set; }

    public virtual FinancialAccount Account { get; set; }

    public virtual ExpensesCategory Category { get; set; }

    public virtual User User { get; set; }
}