// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Event
{
    public Guid EventId { get; set; }

    public string Title { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime EndDateTime { get; set; }

    public string Description { get; set; }

    public string RecurrencePattern { get; set; }

    public DateOnly? RecurrenceEndDate { get; set; }

    public Guid? EvCategoryId { get; set; }

    public Guid? UserId { get; set; }

    public virtual EventCategory EvCategory { get; set; }

    public virtual ICollection<Reminder> Reminders { get; set; } = new List<Reminder>();

    public virtual User User { get; set; }
}