// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class FinancialAccount
{
    public Guid AccountId { get; set; }

    public string AccountName { get; set; }

    public decimal? Balance { get; set; }

    public string CurrencyCode { get; set; }

    public Guid? UserId { get; set; }

    public bool? IsDefault { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual User User { get; set; }
}