// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Goal
{
    public Guid GoalId { get; set; }

    public string GoalName { get; set; }

    public string Description { get; set; }

    public DateOnly TargetDate { get; set; }

    public string Status { get; set; }

    public Guid UserId { get; set; }

    public virtual User User { get; set; }
}