// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Investment
{
    public Guid InvestmentId { get; set; }

    public string InvestmentName { get; set; }

    public decimal Amount { get; set; }

    public DateOnly InvestmentDate { get; set; }

    public DateOnly? MaturityDate { get; set; }

    public decimal? InterestRate { get; set; }

    public Guid UserId { get; set; }

    public virtual User User { get; set; }
}