// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class MembershipPlan
{
    public Guid MPid { get; set; }

    public string PlanName { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}