// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PaymentGateway
{
    public Guid GatewayId { get; set; }

    public string GatewayName { get; set; }

    public string ApiKey { get; set; }

    public bool? IsActive { get; set; }
}