// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PriorityLevel
{
    public byte PriorityId { get; set; }

    public string LevelName { get; set; }

    public string ColorCode { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}