// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ReminderTemplate
{
    public Guid TemplateId { get; set; }

    public string TemplateName { get; set; }

    public string TriggerType { get; set; }

    public int? TriggerValue { get; set; }

    public virtual ICollection<Reminder> Reminders { get; set; } = new List<Reminder>();
}