// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Reminder
{
    public Guid ReminderId { get; set; }

    public DateTime ReminderTime { get; set; }

    public string Status { get; set; }

    public string NotificationChannel { get; set; }

    public Guid? EventId { get; set; }

    public Guid? AssignmentId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? TemplateId { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Event Event { get; set; }

    public virtual ReminderTemplate Template { get; set; }

    public virtual User User { get; set; }
}