// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Subject
{
    public Guid SubjectId { get; set; }

    public string SubjectName { get; set; }

    public string Description { get; set; }
    public Guid UserId { get; set; } // ADD THIS LINE

    public virtual User User { get; set; } // ADD THIS LINE

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}