// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TimeLog
{
    public Guid LogId { get; set; }

    public Guid? AssignmentId { get; set; }

    public Guid? EventId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int? Duration { get; set; }

    public Guid UserId { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}